name: kakarot-screen-patch Win64

on: 
  pull_request:
  push:
  release: 
    types: published
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
       platform: [Win64]
       buildtype: [Debug, Release]
    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v2
      with:
       submodules: 'true'       
    - name: Configure build
      run: ./premake5 vs2019
    - name: Build
      run: |
        msbuild -m project_files/kakarot-screen-patch.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
    - name: Pack artifacts
      run: |
        7z a kakarot-screen-patch_${{matrix.platform}}_${{matrix.buildtype}}.zip ./output/asi/*
    - name: Upload artifact to actions
      uses: actions/upload-artifact@v2
      with:
       name: kakarot-screen-patch${{env.BUILD_CONFIGURATION}}
       path: ./output/asi/*
